pwm_frequency: 47.2
pwm_ms_bias: 0.055


thruster_ch_list: [0, 3, 4, 5]
thruster_topic_list: [control/thruster/heave_bow, 
                      control/thruster/heave_stern, 
                      control/thruster/sway_stern, 
                      control/thruster/surge ]
thruster_min_us: [1100, 1100, 1100, 1100]
thruster_max_us: [1900, 1900, 1900, 1900]
thruster_init_us: [1500, 1500, 1500, 1500]